Split up conditions
CybercentreCanada/assemblyline-ui pull request #20
Opened 2020-09-09 17:30 UTC by cccs-rs

2020-09-09 18:00 UTC, cccs-kevin requested changes
Based on discussion with @cccs-rs, test case needs to be tweaked, and conditional code refactored.

2020-09-09 18:23 UTC, cccs-douglass commented on assemblyline_ui/api/v4/service.py
> +    if delta.get("update_config", None):
It might look a little cleaner/read a little faster written
```if "update_config" in delta:```

2020-09-09 18:23 UTC, cccs-douglass commented on assemblyline_ui/api/v4/service.py
> +    if delta.get("update_config", None):
Though it could be set with a falsely value like `{}` so maybe not

2020-09-09 18:24 UTC, cccs-kevin commented on assemblyline_ui/api/v4/service.py
> +        if delta.get("update_config", {}).get("sources", None):
since we've confirmed at this point that `update_config` exists, we can do a hard lookup -> `delta["update_config"].get("sources", None):`

2020-09-09 18:25 UTC, cccs-kevin commented on assemblyline_ui/api/v4/service.py
> +    if delta.get("update_config", None):
The default of a soft lookup is None, so this is redundant -> `delta.get("update_config")

2020-09-09 18:34 UTC, cccs-kevin commented on assemblyline_ui/api/v4/service.py
> +    if delta.get("update_config", None):
From my discussion with Ryan, if `"update_config"` exists in `delta`, then it has at minimum the value `{"sources": []}`, so this is the correct approach

2020-09-09 19:11 UTC, cccs-kevin commented on test/test_service.py
> +
The majority of code in this test case is the same as in the test case above. Consider using Pytest Fixtures in order to reduce repeated code.

2020-09-10 13:38 UTC, cccs-rs commented on test/test_service.py
> +
I decided to create an additional function that has a parameter for source change, I don't think it would allow me to use a pytest fixture unless I just did the init part

2020-09-10 13:49 UTC, cccs-kevin commented on test/test_service.py
> +
You're definitely on the right track and the code is looking much better. [Pytest Fixtures](https://docs.pytest.org/en/stable/fixture.html) are used for the init part. Also only functions whose names start with "test" should have `assert` statements in them.

2020-09-11 12:53 UTC, cccs-kevin commented on test/test_service.py
> +    assert suricata_change_config(service_conf, login_session)
Nitpick. This isn't very transparent, maybe something like:
`config_changed = suricata_change_config(service_conf, login_session)`
`assert config_changed`
?

2020-09-11 12:54 UTC, cccs-kevin commented on test/test_service.py
> +    assert init_pass
Same here re: transparency of unit tests

2020-09-11 13:07 UTC, cccs-kevin approved these changes

2020-09-11 13:15 UTC, merged