Guard analysis-by-hash against file classification tampering
CybercentreCanada/assemblyline-ui pull request #431
Opened 2022-05-16 18:54 UTC by cccs-rs

2022-05-16 20:25 UTC, cccs-sgaron requested changes

2022-05-16 20:25 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/ingest.py
> +                fileinfo = STORAGE.file.get_if_exists(sha256, as_obj=False)
You've forgot to add the archive_access param.

`archive_access=config.datastore.ilm.update_archive`

2022-05-16 20:25 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/ingest.py
> +                                                            ignore_invalid=True):
We should not ignore invalid classification.

2022-05-16 20:25 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/submit.py
> +                                                            ignore_invalid=True):
We should not ignore invalid classification

2022-05-16 20:25 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/submit.py
> +                fileinfo = STORAGE.file.get_if_exists(sha256, as_obj=False)
You've forgot to add the archive_access param.

`archive_access=config.datastore.ilm.update_archive`

2022-05-17 14:01 UTC, cccs-sgaron approved these changes

2022-05-17 14:10 UTC, cccs-douglass approved these changes

2022-05-17 14:19 UTC, merged