Favorites parsing
CybercentreCanada/assemblyline-ui pull request #719
Opened 2023-08-29 16:36 UTC by cccs-nr

Added a function that parses the favorites to the right format and removes any duplicate favorite with the same name.

2023-09-05 17:45 UTC, cccs-rs approved these changes

2023-09-05 17:48 UTC, cccs-rs requested changes
Tests aren't passing

2023-09-06 18:44 UTC, cccs-nr commented
The tests were fixed on the classification-tests branch. I copied them over.

2023-09-06 18:54 UTC, cccs-rs approved these changes

2023-09-14 12:29 UTC, merged