SAML Authentication
CybercentreCanada/assemblyline-ui pull request #942
Opened 2024-05-14 17:35 UTC by CyDefender

Adds support for SAML Authentication: https://github.com/CybercentreCanada/assemblyline/issues/25

2024-05-15 13:30 UTC, cccs-sgaron requested changes
Some changes are required

2024-05-15 13:30 UTC, cccs-sgaron commented on assemblyline_ui/security/saml_auth.py
> +        elif config.auth.internal.enabled:
Following elif and else are not required, the function should just return None, None

2024-05-15 13:30 UTC, cccs-sgaron commented on assemblyline_ui/security/saml_auth.py
> +    return None
This will crash, should return None, None

2024-05-15 19:21 UTC, CyDefender commented on assemblyline_ui/api/v4/authentication.py
> +        resp = make_response(metadata, 200)
The response is XML. I think the `make_api_response` is expecting JSON.

2024-05-15 19:27 UTC, CyDefender commented on assemblyline_ui/api/v4/authentication.py
> +        # TODO we need the equivalent of oath's `provider.authorize_redirect`
I don't think so, since the identity provider is defined in the AL config.  SAML doesn't use various providers like OAuth. It's more like LDAP, where you direct it to your auth host.  I'll remove that TODO.

2024-05-15 19:30 UTC, CyDefender commented on assemblyline_ui/api/v4/authentication.py
> +        # TODO we need the equivalent of oath's `provider.authorize_redirect`
I didn't get any CORS errors in my testing, but there is someplace we need to define a authorized redirect, we can get that from the saml config.

2024-05-16 11:58 UTC, cccs-sgaron approved these changes

2024-05-16 14:20 UTC, cccs-sgaron commented
Closed in favor of: https://github.com/CybercentreCanada/assemblyline-ui/pull/945

2024-05-16 14:20 UTC, closed without merging