Added support for using WorkloadIdentity Auth
CybercentreCanada/assemblyline-ui pull request #971
Opened 2024-06-26 15:22 UTC by ociappara

Allow users to auth with WorkloadIdentityCredential

2024-06-26 15:23 UTC, ociappara commented
Still working on testing end to end code changes

2024-06-26 15:40 UTC, cccs-rs commented on assemblyline_ui/api/v4/authentication.py
> +                        additionally_allowed_tenants=[oauth_provider_config.client_tenent])
oauth_provider_config.client_tenent should already be a list of strings, haven't looked into the class but I assume it doesn't require a `List[List[str]]`?

2024-06-26 15:52 UTC, cccs-sgaron requested changes

2024-06-26 15:52 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/authentication.py
> +                if (oauth_provider_config.validate_token_with_secret or oauth_provider_config.app_provider) and not token:
this should just be an else if and you would not have to add the "and not token"

2024-06-26 16:01 UTC, cccs-sgaron commented on assemblyline_ui/api/v4/authentication.py
> +                        , tenant_id=oauth_provider_config.client_tenent)
Same typo as the base repo. **client_tenent** => **client_tenants**

2024-06-26 16:06 UTC, C-Oliver commented on assemblyline_ui/api/v4/authentication.py
> +                        additionally_allowed_tenants=[oauth_provider_config.client_tenent])
Done.

2024-06-26 16:06 UTC, C-Oliver commented on assemblyline_ui/api/v4/authentication.py
> +                if (oauth_provider_config.validate_token_with_secret or oauth_provider_config.app_provider) and not token:
Done.

2024-07-02 10:16 UTC, ociappara commented
Are we okay to merge this to Dev ?

2024-07-08 13:14 UTC, cccs-sgaron commented
Merging it into dev as: https://github.com/CybercentreCanada/assemblyline-ui/pull/978

2024-07-09 13:27 UTC, cccs-sgaron approved these changes

2024-07-09 14:12 UTC, merged